// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwauwjnwnperezygoubu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3YXV3am53bnBlcmV6eWdvdWJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMzMyNTIsImV4cCI6MjA1OTYwOTI1Mn0.uf2tXTtK3bnWPntgCQwOStVv67ovOx3dlbmi1mrj2-Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);